module.exports = {
  BOT_TOKEN: (process.env.BOT_TOKEN || '').trim(),
  CHAT_ID: (process.env.CHAT_ID || '').trim(),
  BYBIT_API_KEY: (process.env.BYBIT_API_KEY || '').trim(),
  BYBIT_API_SECRET: (process.env.BYBIT_API_SECRET || '').trim(),
  ALERT_INTERVAL_MS: Number(process.env.ALERT_INTERVAL_MS || 360000),
  FUNDING_THRESHOLD: Number(process.env.FUNDING_THRESHOLD || 0.01),
  VOLUME_SPIKE_THRESHOLD: Number(process.env.VOLUME_SPIKE_THRESHOLD || 1.5),
  MIN_SCORE: Number(process.env.MIN_SCORE || 70),
  MIN_TURNOVER_24H: Number(process.env.MIN_TURNOVER_24H || 5000000),
  MIN_RR: Number(process.env.MIN_RR || 1.5),
  OI_ACCEL_THRESHOLD: Number(process.env.OI_ACCEL_THRESHOLD || 0.3),
  LIVE_TRADING: (process.env.LIVE_TRADING || 'false') === 'true',
  AUTO_TRADING: (process.env.AUTO_TRADING || 'true') === 'true',
  BYBIT_BASE: process.env.BYBIT_BASE || 'https://api.bybit.com',
  ORDER_USDT: Number(process.env.ORDER_USDT || 25),
  LEVERAGE: Number(process.env.LEVERAGE || 5),
  MAX_OPEN_TRADES: Number(process.env.MAX_OPEN_TRADES || 1),
  TRAILING_STOP_PCT: Number(process.env.TRAILING_STOP_PCT || 1.2)
};
