module.exports = {
  BOT_TOKEN: (process.env.BOT_TOKEN || '').trim(),
  CHAT_ID: (process.env.CHAT_ID || '').trim(),
  BYBIT_API_KEY: (process.env.BYBIT_API_KEY || '').trim(),
  BYBIT_API_SECRET: (process.env.BYBIT_API_SECRET || '').trim(),
  BYBIT_BASE: process.env.BYBIT_BASE || 'https://api.bybit.com',
  LIVE_TRADING: (process.env.LIVE_TRADING || 'false') === 'true',
  MAX_OPEN_TRADES: Number(process.env.MAX_OPEN_TRADES || 1),
  ORDER_USDT: Number(process.env.ORDER_USDT || 25),
  LEVERAGE: Number(process.env.LEVERAGE || 5),
  RISK_PERCENT: Number(process.env.RISK_PERCENT || 1),
  MIN_SCORE: Number(process.env.MIN_SCORE || 70),
  MIN_TURNOVER_24H: Number(process.env.MIN_TURNOVER_24H || 5000000),
  ONLY_NEW_DAYS: Number(process.env.ONLY_NEW_DAYS || 90),
  REST_REFRESH_MS: Number(process.env.REST_REFRESH_MS || 30000),
  STATE_FILE: process.env.STATE_FILE || 'state.json',
};
