const http = require('http');
const TelegramBot = require('node-telegram-bot-api');
const cfg = require('./config');
const { loadState, saveState } = require('./state');
const bybit = require('./bybit');

const state = loadState();
state.activeTrades = state.activeTrades || [];
state.closedTrades = state.closedTrades || [];
state.lastAlerts = state.lastAlerts || {};
state.seenNews = state.seenNews || [];

const BOT = cfg.BOT_TOKEN ? new TelegramBot(cfg.BOT_TOKEN, { polling: { interval: 1000, autoStart: true, params: { timeout: 10 } } }) : null;
const PORT = Number(process.env.PORT || 10000);
const server = http.createServer((_, res) => { res.writeHead(200); res.end('OK'); });
server.listen(PORT, '0.0.0.0');

function log(m){ console.log(`[${new Date().toISOString()}] ${m}`); }
function num(v){ const x = Number(v); return Number.isFinite(x) ? x : null; }
function mean(a){ return a.length ? a.reduce((s,x)=>s+x,0)/a.length : 0; }
function std(a){ const m = mean(a); return a.length ? Math.sqrt(mean(a.map(x => (x-m)*(x-m)))) : 0; }
function ema(vals,p){ if(!vals.length) return []; const k=2/(p+1); let prev=vals[0]; const out=[prev]; for(let i=1;i<vals.length;i++){ prev = vals[i]*k + prev*(1-k); out.push(prev); } return out; }
function atr(candles,p=14){ const trs=[]; for(let i=1;i<candles.length;i++){ const c=candles[i], pr=candles[i-1]; trs.push(Math.max(c.high-c.low, Math.abs(c.high-pr.close), Math.abs(c.low-pr.close))); } return ema(trs,p); }
function clamp(n,a,b){ return Math.max(a, Math.min(b,n)); }
function roundQty(q){ return Math.max(Number(q.toFixed(3)), 0.001); }
function parseCandles(list){ return list.map(x => ({ start:+x[0], open:+x[1], high:+x[2], low:+x[3], close:+x[4], volume:+x[5] })); }
function tradeKey(t){ return `${t.symbol}:${t.side}:${t.entry}`; }
function botSend(text){ if(!BOT || !cfg.CHAT_ID) return Promise.resolve(false); return BOT.sendMessage(cfg.CHAT_ID, text, { disable_web_page_preview: true }).catch(()=>false); }
function statusText(){ return [`v29 AUTO`, `LIVE: ${cfg.LIVE_TRADING ? 'ON' : 'OFF'}`, `open trades: ${state.activeTrades.length}`, `closed trades: ${state.closedTrades.length}`, `min score: ${cfg.MIN_SCORE}`, `order: ${cfg.ORDER_USDT} USDT`, `lev: ${cfg.LEVERAGE}x`].join('\n'); }

async function getUniverse(){ const rows = await bybit.getSymbols(); return rows.filter(r => (num(r.turnover24h)||0) >= cfg.MIN_TURNOVER_24H); }
async function scoreSymbol(symbol){ const [k15raw, k60raw, oi, fund, tick] = await Promise.all([bybit.getKlines(symbol,'15',120), bybit.getKlines(symbol,'60',120), bybit.getOI(symbol,'60',20), bybit.getFunding(symbol), bybit.getTicker(symbol)]); const k15=parseCandles(k15raw), k60=parseCandles(k60raw); if(k15.length<60||k60.length<60) return null; const c15=k15.map(x=>x.close), c60=k60.map(x=>x.close), v15=k15.map(x=>x.volume); const e20=ema(c15,20), e50=ema(c15,50), e60=ema(c60,50), e200=ema(c60,200); const a15=atr(k15,14); const volAvg=mean(v15.slice(-20))||1; const volStd=std(v15.slice(-20))||1; const volSpike=(v15[v15.length-1]-volAvg)/volStd; const last=k15[k15.length-1], prev=k15[k15.length-2]; const bullish1h = c60[c60.length-1] > e60[e60.length-1] && e60[e60.length-1] > e200[e200.length-1]; const bullish15 = e20[e20.length-1] > e50[e50.length-1] || e20[e20.length-2] <= e50[e50.length-2]; const breakout = last.close > Math.max(...k15.slice(-10,-1).map(c=>c.high)); const retest = prev.close <= Math.max(...k15.slice(-10,-1).map(c=>c.high)) && last.close > e20[e20.length-1]; const price = tick ? num(tick.lastPrice) : last.close; const change24h = tick ? num(tick.price24hPcnt)*100 : 0; const turnover = tick ? num(tick.turnover24h) : 0; const oiVals = oi.map(x => num(x.openInterest)).filter(Boolean); const oiChg = oiVals.length>2 ? ((oiVals[0]-oiVals[oiVals.length-1])/oiVals[oiVals.length-1])*100 : 0; const oiAccel = oiVals.length>3 ? (((oiVals[0]-oiVals[Math.floor(oiVals.length/2)])/oiVals[Math.floor(oiVals.length/2)]) - ((oiVals[Math.floor(oiVals.length/2)]-oiVals[oiVals.length-1])/oiVals[oiVals.length-1]))*100 : 0; const funding = fund?.[0] ? num(fund[0].fundingRate) : 0; const ageScore = 10; const volumeScore = clamp(turnover / 300000, 0, 20); const momentumScore = clamp(change24h * 1.3, 0, 20); const inPlay = clamp((volSpike * 4) + ((a15[a15.length-1] / mean(a15.slice(-30) || [1])) - 1) * 8, 0, 20); const trend = bullish1h ? 15 : 0; const trigger = bullish15 && (breakout || retest) ? 20 : 0; const oiScore = clamp(oiChg * 0.8 + oiAccel * 0.4, -10, 20); const fundingScore = funding < 0 ? 8 : 0; const score = Math.round(ageScore + volumeScore + momentumScore + inPlay + trend + trigger + oiScore + fundingScore); const status = score >= cfg.MIN_SCORE && bullish1h && bullish15 && (breakout || retest) ? 'LONG' : 'WAIT'; const entry = price; const stop = Math.min(...k15.slice(-10).map(c=>c.low), entry - (a15[a15.length-1] || entry*0.01)); const risk = Math.max(entry - stop, 1e-8); const tp1 = entry + risk * 1.5; const tp2 = entry + risk * 3.5; return { symbol, status, score, entry, stop, tp1, tp2, bullish1h, bullish15, breakout, retest, turnover, change24h, oiChg, oiAccel, funding, price, atr: a15[a15.length-1] || 0 }; }
async function openTrade(sig){ if(!cfg.LIVE_TRADING) return; if(state.activeTrades.length >= cfg.MAX_OPEN_TRADES) return; const pos = await bybit.getPosition(sig.symbol).catch(()=>null); if(pos && Math.abs(num(pos.size)||0) > 0) return; const qty = roundQty((cfg.ORDER_USDT * cfg.LEVERAGE) / sig.entry); const side = 'Buy'; const order = await bybit.placeOrder({ symbol: sig.symbol, side, qty, orderType:'Market' }); await bybit.setTradingStop({ symbol: sig.symbol, takeProfit: sig.tp1, stopLoss: sig.stop, trailingStop: sig.entry * 0.012, activePrice: sig.entry }); state.activeTrades.push({ symbol: sig.symbol, side, qty, entry: sig.entry, stop: sig.stop, tp1: sig.tp1, tp2: sig.tp2, openedAt: Date.now(), orderId: order?.result?.orderId || null, key: tradeKey({symbol:sig.symbol,side,entry:sig.entry}) }); saveState(state); await botSend(`OPEN ${sig.symbol}\nscore ${sig.score}\nentry ${sig.entry}\nSL ${sig.stop}\nTP1 ${sig.tp1}\nTP2 ${sig.tp2}`); log(`opened ${sig.symbol}`); }
async function closeTrade(t, reason='manual'){ if(!cfg.LIVE_TRADING) return; try{ await bybit.cancelAll(t.symbol); const pos = await bybit.getPosition(t.symbol); const size = Math.abs(num(pos?.size)||t.qty); if(size>0){ const side = (pos?.side||t.side) === 'Buy' ? 'Sell' : 'Buy'; await bybit.placeOrder({ symbol: t.symbol, side, qty: roundQty(size), orderType:'Market', reduceOnly:true }); } } finally { state.activeTrades = state.activeTrades.filter(x => x.symbol !== t.symbol); state.closedTrades.unshift({...t, closedAt: Date.now(), reason}); state.closedTrades = state.closedTrades.slice(0,200); saveState(state); await botSend(`CLOSE ${t.symbol}\nreason ${reason}`); log(`closed ${t.symbol} ${reason}`); } }
async function manageTrades(){ const keep=[]; for(const t of state.activeTrades){ const pos = await bybit.getPosition(t.symbol).catch(()=>null); if(!pos || Math.abs(num(pos.size)||0) === 0){ state.closedTrades.unshift({...t, closedAt: Date.now(), reason:'closed-by-exchange'}); continue; } const last = num(pos.markPrice) || num(pos.avgPrice) || t.entry; if(last >= t.tp2) { await closeTrade(t,'tp2'); continue; } if(last <= t.stop) { await closeTrade(t,'stop'); continue; } keep.push(t); } state.activeTrades = keep; saveState(state); }
async function scan(){ const uni = await getUniverse(); const results = []; for(const row of uni.slice(0,25)){ const sig = await scoreSymbol(row.symbol).catch(e => { log(`score err ${row.symbol} ${e.message}`); return null; }); if(!sig) continue; results.push(sig); if(sig.status === 'LONG'){ const fp = `${sig.symbol}:${sig.entry.toFixed(8)}:${sig.score}`; if(state.lastAlerts[sig.symbol] !== fp){ state.lastAlerts[sig.symbol] = fp; saveState(state); await botSend(`SIGNAL ${sig.symbol}\nscore ${sig.score}\nentry ${sig.entry}\nSL ${sig.stop}\nTP1 ${sig.tp1}\nTP2 ${sig.tp2}`); await openTrade(sig); } } } results.sort((a,b)=>b.score-a.score); state.lastResults = results.slice(0,20); saveState(state); if(results[0]) log(`top ${results[0].symbol} score=${results[0].score} status=${results[0].status}`); else log('no candidates'); }
async function loop(){ while(true){ try{ await scan(); await manageTrades(); } catch(e){ log(`loop err ${e.message}`); } await new Promise(r => setTimeout(r, cfg.REST_REFRESH_MS)); } }
if(BOT){ BOT.on('polling_error', e => log(`telegram ${e.message}`)); BOT.on('message', m => { if(!m.text) return; const t=m.text.trim().toLowerCase(); if(t==='status' || t==='/status') return BOT.sendMessage(m.chat.id, statusText()); if(t==='trades' || t==='/trades') return BOT.sendMessage(m.chat.id, state.activeTrades.length ? JSON.stringify(state.activeTrades,null,2) : 'no active trades'); }); }
(async()=>{ log('boot'); await botSend('v29 started\n' + statusText()); setInterval(()=>saveState(state),10000); setInterval(()=>log(`heartbeat open:${state.activeTrades.length}`),120000); await loop(); })().catch(e => { log(`fatal ${e.message}`); process.exit(1); });
